- name: Collect log files from Control Node
  hosts: Server1
  gather_facts: no
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Find all .log files
      find:
        paths: "/var/log"
        patterns: "*.log"
        recurse: yes
      register: log_files

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "~/hoa7/logs"
        state: directory
        owner: janssenvalencia  
        group: janssenvalencia  
        mode: "0755"  
      become_user: janssenvalencia

    - name: Fetch each log file
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "~/hoa7/logs"
        flat: yes
      with_items: "{{ log_files.files }}"

